### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by michael-a-grammar** [SimpleBet/opentelemetry_commanded#14]
Hi,

Is this repo still maintained? If not, would it be possible for my organisation [Prima.it](https://github.com/primait) to take ownership?

Cheers

**Comment by davydog187** [comment]
Hello @milquetoastable, we are in the process of getting this project back off the ground.

Please send pull requests if you are interested in improving the project and we will be happy to review!

**Comment by michael-a-grammar** [comment]
Brilliant, thank you!

**Comment by davydog187** [comment]
@milquetoastable i now have maintainer access on this project. Are you interested in helping close any of the open issues?
